# Workflow definition for compiling and running the tests for the master branch.
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup of JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      # Compile phase
      - name: Compile the project with Maven
        run: mvn compile

      # Test phase
      - name: Run the tests with Maven
        env:
          REGION: ${{ secrets.REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: mvn test failsafe:integration-test

      # Generate code coverage report
      - name: Generate code coverage report
        run: mvn jacoco:report

      # Code coverage
      - name: Upload code coverage report
        uses: codecov/codecov-action@v1

      # Archive
      - name: Prepare artifacts
        run: mvn clean package -Dmaven.test.skip=true

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: krokodil-app
          path: ./target/krokodil-*.jar