# Workflow definition for compiling and running the tests for the master branch.
name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Setup of JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Cache java setup
        uses: actions/upload-artifact@master
        with:
          name: java-setup
          path: /opt/hostedtoolcache/Java_Adopt_jdk/16.*/x64

  compile-main:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/download-artifact@master
        with:
          name: java-setup
          path: /opt/hostedtoolcache/Java_Adopt_jdk/16.*/x64
      - uses: actions/checkout@v2
      - name: Compile the main sources
        run: mvn compile
      - uses: actions/upload-artifact@master
        with:
          name: compiled-source
          path: ./target

  compile-test:
    runs-on: ubuntu-latest
    needs: compile-main
    steps:
      - uses: actions/download-artifact@master
        with:
          name: main-compiled
          path: ./target
      - name: Compile the test sources
        run: mvn test-compile

  unit-tests:
    runs-on: ubuntu-latest
    needs: compile-test
    steps:
      - name: Run the unit tests
        run: mvn test

  integration-tests:
    runs-on: ubuntu-latest
    needs: compile-test
    steps:
      - name: Run the integration tests
        env:
          REGION: ${{ secrets.REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: mvn failsafe:integration-test

  coverage:
    runs-on: ubuntu-latest
    needs: [ unit-tests, integration-tests ]
    steps:
      - name: Generate the code coverage file
        run: mvn jacoco:report
      - name: Upload the code coverage file
        uses: codecov/codecov-action@v1
